name: monifly-v2
services:
- name: api
  source_dir: backend
  github:
    repo: JuanGilles123/monifly-v2
    branch: master
  run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080
  build_command: pip install -r requirements.txt && alembic upgrade head || true
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /healthz
  envs:
  - key: CORS_ORIGINS
    value: https://app.monifly.app
    
- name: frontend  
  type: STATIC_SITE
  source_dir: frontend
  github:
    repo: JuanGilles123/monifly-v2
    branch: master
  build_command: npm ci && npm run build
  output_dir: dist
  envs:
  - key: VITE_API_URL
    value: https://api.monifly.app
